#ifndef WIFI_MANAGER_INCLUDE_WIFI_PROVISIONING_EVENTS_H_
#define WIFI_MANAGER_INCLUDE_WIFI_PROVISIONING_EVENTS_H_

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(WIFI_MANAGER_PROVISIONING_EVENTS);

enum {                                      
    PROVISIONING_COMPLETED,
    PROVISIONING_FAILED
};

#endif